### ISSUE TITLE
Error when install ELK mpack-3.0.0.0-1

### ISSUE THREAD

**Issue by mediapills** [steven-dfheinz/dfhz_elk_mpack#1]
I am trying to install `elasticsearch_mpack-3.0.0.0-1.tar.gz` using command:
```
$ ambari-server install-mpack --mpack=https://github.com/steven-matison/dfhz_elk_mpack/raw/master/elasticsearch_mpack-3.0.0.0-1.tar.gz --verbose
```

Here is the trace back what I am getting during service setup via `Ambari UI`:
```
Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/stack-hooks/before-ANY/scripts/hook.py", line 38, in <module>
    BeforeAnyHook().execute()
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/script/script.py", line 351, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/stack-hooks/before-ANY/scripts/hook.py", line 31, in hook
    setup_users()
  File "/var/lib/ambari-agent/cache/stack-hooks/before-ANY/scripts/shared_initialization.py", line 50, in setup_users
    groups = params.user_to_groups_dict[user],
KeyError: u'logstash'
Error: Error: Unable to run the custom hook script ['/usr/bin/python', '/var/lib/ambari-agent/cache/stack-hooks/before-ANY/scripts/hook.py', 'ANY', '/var/lib/ambari-agent/data/command-603.json', '/var/lib/ambari-agent/cache/stack-hooks/before-ANY', '/var/lib/ambari-agent/data/structured-out-603.json', 'INFO', '/var/lib/ambari-agent/tmp', 'PROTOCOL_TLSv1_2', '']
```
I also have tried to run:
```
$ yum --disablerepo=* --enablerepo=epel search elasticsearch
```

**ambari-agent**: 2.7.1.0-169
**HDP**: 3.0.1_virtualbox_181205

**Comment by steven-matison** [comment]
Sorry for such a late response,  git is not sending notifications for issues.  

You need to execute the user/group management python script to disable user/group management:

python /var/lib/ambari-server/resources/scripts/configs.py -u admin -p admin -n [CLUSTER_NAME] -l [CLUSTER_FQDN] -t 8080 -a set -c cluster-env -k  ignore_groupsusers_create -v true


I have not found a better solution.

**Comment by steven-matison** [comment]
I got this reply on a stack post I made regarding the user group error awhile back:

https://stackoverflow.com/questions/62217699/ambari-user-group-management-for-custom-ambari-services/65081701#65081701

I need to take a run at the mpack and see if there is a way to work around the issue based on this info.
